name: run script

on:
  schedule:
    - cron: '0 0 1 * *' # This cron expression schedules the job to run at midnight on the first day of each month
  workflow_dispatch: # add run button in github

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Commit updated data bundle
      if: success()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: "geojson/itos-*.geojson"
        commit_message: automatic - geojson updated
        push_options: "--force"
        skip_dirty_check: false